Yeebase:
  TwoFactorAuthentication:
    # Length of the secret key that is created for the validation of secrets
    # The length given here is multiplied with 8 as the key must be at least 8 chars and be a power of 2
    secretKeyLength: 2

    # The application name that should appear in the authenticator app
    applicationName: 'default'

    # The target of the redirect which is issued when no Two-Factor-Authentication secret is specified
    authenticationEntryPoint:
      package: ~
      controller: ~
      action: 'insertSecret'
